services:
  broker:
    build:
      context: ./broker
    ports:
      - "8883:8883"
    container_name: broker
    networks:
      - backend
  
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    # Port 5432 usunięty zgodnie z instrukcją (brak publicznej ekspozycji)
    image: database:v1
    container_name: postgres
    networks:
      - backend

  ingestor:
    build:
      context: ./ingestor
      dockerfile: Dockerfile
    container_name: ingestor
    depends_on:
    - broker
    - database
    networks:
      - backend

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    container_name: api
    depends_on:
      - database
    networks:
      - backend


networks:
  backend:
    driver: bridge